SiteTree:
  extensions:
    - MetaTitleExtension
MetaTitleExtension:
  InsertBefore: 'MetaDescription'
NewsHolder:
    extensions:
      - WidgetPageExtension
Page:
    extensions:
      - WidgetPageExtension
Student:
  extensions:
    - Addressable
    - Geocodable